=== InseeFr/Magma/magma-oas/src/main/resources/rapport-qualite.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://magma.insee/rapport-qualite.schema.json",
  "title": "RapportQualite",
  "description": "Rapport qualité",
  "type": "object",
  "properties": {
    "id": {
      "description": "Identifiant rapport qualité",
      "type": "string"
    },
    "uri": {
      "description": "URI du schema",
      "type": "string",
      "format": "uri"
    },
    "label": {
      "description": "Labels localisés",
      "type": "array",
      "items": {
        "$ref": "langue-contenu.schema.json"
      }
    },
    "rubriques": {
      "description": "Rubriques composant le rapport",
      "type": "array",
      "items": {
        "$ref": "rubrique.schema.json"
      }
    }
  },
  "required": ["id","uri","label","rubriques"]
}

=== InseeFr/Magma/magma-oas/src/test/resources/rapport-qualite-1979.json
{

"id": "1979",

"uri": "http://id.insee.fr/qualite/rapport/1979",

"label": [

{

"contenu": "Rapport qualité : Enquête emploi en continu 2020",

"langue": "fr"

},

{

"contenu": "Quality report: Labour force survey 2020",

"langue": "en"

}

],

"rubriques": [

{

"id": "I.18.7",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.18.7",

"idParent": "S.18",

"type": "RICH_TEXT",

"titre": [

{

"contenu": "Période de collecte",

"langue": "fr"

},

{

"contenu": "Data collection period",

"langue": "en"

}

],

"contenus": [

{

"texte": "<p>La collecte est réalisée en continu sur toutes les semaines de l'année.<br />\nLa collecte s'effectue, sauf exception, dans les 2 semaines et 2 jours après la fin de la semaine de référence.<br />\nChaque logement est enquêté six trimestres de suite.</p>",

"langue": "fr"

},

{

"texte": "<p>The data collection is conducted continuously, every week of the year. The interview is usually conducted in the 2 weeks and 2 days following the reference week.<br />\nEach dwelling is surveyed six consecutive quarters.</p>",

"langue": "en"

}

]

},

{

"id": "S.3.8",

"uri": "http://ec.europa.eu/eurostat/simsv2/attribute/S.3.8",

"idParent": "S.3",

"type": "TEXT",

"label": [

{

"contenu": "<p>L'ensemble de l'année.</p>",

"langue": "fr"

},

{

"contenu": "<p>The complete year.</p>",

"langue": "en"

}

],

"titre": [

{

"contenu": "Couverture temporelle",

"langue": "fr"

},

{

"contenu": "Time coverage",

"langue": "en"

}

]

},

{

"id": "S.3.7",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/S.3.7",

"idParent": "S.3",

"type": "GEOGRAPHY",

"titre": [

{

"contenu": "Zone géographique de référence",

"langue": "fr"

},

{

"contenu": "Reference area",

"langue": "en"

}

],

"territoire": {

"id": "franceHorsMayotte",

"uri": "http://id.insee.fr/qualite/territoire/franceHorsMayotte",

"label": [

{

"contenu": "France hors Mayotte",

"langue": "fr"

}

]

}

},

{

"id": "I.18.9",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.18.9",

"idParent": "S.18",

"type": "CODE_LIST",

"titre": [

{

"contenu": "Unité(s) enquêtée(s)",

"langue": "fr"

},

{

"contenu": "Survey unit",

"langue": "en"

}

],

"codes": [

{

"id": "H",

"uri": "http://id.insee.fr/codes/uniteEnquetee/H",

"label": [

{

"contenu": "Ménage",

"langue": "fr"

},

{

"contenu": "Household",

"langue": "en"

}

]

}

]

},

{

"id": "I.18.8",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.18.8",

"idParent": "S.18",

"type": "CODE_LIST",

"titre": [

{

"contenu": "Mode de collecte",

"langue": "fr"

},

{

"contenu": "Collection mode",

"langue": "en"

}

],

"codes": [

{

"id": "F",

"uri": "http://id.insee.fr/codes/modeCollecte/F",

"label": [

{

"contenu": "Face à face par enquêteur",

"langue": "fr"

},

{

"contenu": "Face to face by interviewer",

"langue": "en"

}

]

},

{

"id": "P",

"uri": "http://id.insee.fr/codes/modeCollecte/P",

"label": [

{

"contenu": "Par téléphone",

"langue": "fr"

},

{

"contenu": "By phone",

"langue": "en"

}

]

}

]

},

{

"id": "S.3.6",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/S.3.6",

"idParent": "S.3",

"type": "RICH_TEXT",

"titre": [

{

"contenu": "Population statistique",

"langue": "fr"

},

{

"contenu": "Statistical population",

"langue": "en"

}

],

"contenus": [

{

"texte": "<p>Individus de 15 ans ou plus vivant en : <a href=\"https://www.insee.fr/fr/metadonnees/definition/c2056\">logement ordinaire</a>.</p>",

"langue": "fr"

},

{

"texte": "<p>Persons aged 15 or more, living in: <a href=\"https://www.insee.fr/en/metadonnees/definition/c2056\">ordinary housing</a>.</p>",

"langue": "en"

}

]

},

{

"id": "I.6.3",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.6.3",

"idParent": "S.6",

"type": "CODE_LIST",

"titre": [

{

"contenu": "Statut de l'enquête",

"langue": "fr"

},

{

"contenu": "Survey status",

"langue": "en"

}

],

"codes": [

{

"id": "T",

"uri": "http://id.insee.fr/codes/statutEnquete/T",

"label": [

{

"contenu": "Enquête d'intérêt général et de qualité statistique à caractère obligatoire",

"langue": "fr"

},

{

"contenu": "Survey of general interest and statistical quality, with compulsory nature",

"langue": "en"

}

]

}

]

},

{

"id": "I.6.4",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.6.4",

"idParent": "S.6",

"type": "TEXT",

"label": [

{

"contenu": "<p>2018T006EC</p>",

"langue": "fr"

},

{

"contenu": "<p>2018T006EC</p>",

"langue": "en"

}

],

"titre": [

{

"contenu": "n° de visa",

"langue": "fr"

},

{

"contenu": "n° visa",

"langue": "en"

}

]

},

{

"id": "I.18.11",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.18.11",

"idParent": "S.18",

"type": "TEXT",

"label": [

{

"contenu": "<p>Chaque trimestre en moyenne, jusqu'au T3 2019, environ 92 000 logements sont enquêtés, dont 73 000 qui sont  des résidences principales et entrent dans le champ de l'enquête. La taille va progressivement diminuer avec le renouvellement de l'échantillon. Au final, au T4 2020, la taille de l'échantillon sera inférieure d'environ 15 % à celle observée avant.</p>",

"langue": "fr"

},

{

"contenu": "<p>Each quarter, until Q3 2019, 92,000 dwellings are surveyed, 73,000 of which are principal residences and are in the target population. The size will gradually decrease with the renewal of the sample. In the end, in Q4 2020, the sample size will be about 15% smaller.</p>",

"langue": "en"

}

],

"titre": [

{

"contenu": "Taille de l'échantillon",

"langue": "fr"

},

{

"contenu": "Sample size",

"langue": "en"

}

]

},

{

"id": "I.18.12",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.18.12",

"idParent": "S.18",

"type": "RICH_TEXT",

"titre": [

{

"contenu": "Documents de collecte",

"langue": "fr"

},

{

"contenu": "Data collection documents",

"langue": "en"

}

],

"contenus": [

{

"documents": [

{

"label": [

{

"contenu": "Questionnaire EEC 2020",

"langue": "fr"

}

],

"dateMiseAJour": "0010-07-14",

"langue": "fr",

"url": "https://www.insee.fr/fr/metadonnees/source/fichier/EEC2020_Questionnaire.pdf"

},

{

"label": [

{

"contenu": "Questionnaire module complémentaire EEC 2020",

"langue": "fr"

},

{

"contenu": "Ad-hoc module LFS 2020",

"langue": "en"

}

],

"dateMiseAJour": "2020-01-01T00:00:00",

"langue": "fr",

"url": "https://www.insee.fr/fr/metadonnees/source/fichier/QuestionnaireFR-MAD2020.pdf"

}

],

"texte": "",

"langue": "fr"

}

]

},

{

"id": "I.18.10",

"uri": "http://id.insee.fr/qualite/simsv2fr/attribut/I.18.10",

"idParent": "S.18",

"type": "RICH_TEXT",

"titre": [

{

"contenu": "Plan de sondage",

"langue": "fr"

},

{

"contenu": "Sampling method",

"langue": "en"

}

],

"contenus": [

{

"texte": "<p>L'échantillon de l'enquête Emploi est un échantillon de logements, et non d'individus. Il présente deux caractéristiques principales : il est aréolaire (constitué d'un tirage de groupes de logements proches) et rotatif (les logements entrants dans l'échantillon un trimestre donné sont enquêtés pendant six trimestres consécutifs).</p>\n<p>En France métropolitaine, l'échantillon de l'EEC est en cours de renouvellement. À partir du T3 2019, les grappes entrantes (soit 1/6e de l'échantillon) sont issues de ce nouvel échantillon. Ceci va assurer le renouvellement progressif de l'échantillon. Au final, l'échantillon de France métropolitaine sera complètement renouvelé au T4 2020.</p>\n<p>En France métropolitaine, la base de sondage de l'enquête Emploi est constituée :<br />\n- pour l'ancien échantillon, des fichiers de la taxe d'habitation 2006 ;<br />\n- pour le nouvel échantillon, du fichier démographique des logements et des individus 2016 (Fideli).</p>\n<p>En France métropolitaine, le tirage de l'échantillon est stratifié par région. Au sein de chaque région, le tirage des secteurs est fait de manière &lt;&lt; équilibrée &gt;&gt;, proportionnellement au nombre de résidences principales, selon des caractéristiques de la base de sondage.</p>\n<p>Pour les DOM, il s'agit d'un échantillonnage stratifié (selon des zones géographiques) à un degré, avec tirage systématique de logements à probabilités égales au sein de chaque strate.</p>\n<p>L'échantillon est uniformément réparti sur les 13 semaines de chaque trimestre ; chaque grappe est affectée à une semaine &lt;&lt; de référence &gt;&gt;.</p>\n<p>Le taux de sondage moyen est de 1/400.</p>\n<p>Le module complémentaire est posé aux grappes entrantes et sortantes.</p>",

"langue": "fr"

},

{

"texte": "<p>The sampling unit is dwelling. The sample is rotational: each cluster is surveyed 6 consecutive quarters, then replaced by a new cluster of the same sector.</p>\n<p>In Metropolitan France, the sample is currently being renewed. As of Q3 2019, each new cluster (1st wave : 1/6th of the sample) belongs to the new sample. This will ensure the gradual renewal of the sample. In the end, the sample from Metropolitan France will be completely renewed in Q4 2020. The sampling frame is the housing-tax register for the old sample and the demographic file of dwellings and individuals (&lt;&lt; Fideli &gt;&gt;) for the new sample.  The sample selection is stratified by region. For each region, the sample is balanced, proportionnaly of the number of main residences, on some variables from the sampling frame.</p>\n<p>For DOM, the sampling is stratified (geographic strata) and systematic (with equal inclusion probabilities, within geographic strata).</p>\n<p>The sample is uniformely distributed among the 13 weeks of the quarter. Each cluster is affected to a reference week.</p>\n<p>The complementary module is asked to the ingoing and outgoing clusters.</p>",

"langue": "en"

}

]

},

{

"id": "S.4",

"uri": "http://ec.europa.eu/eurostat/simsv2/attribute/S.4",

"type": "TEXT",

"label": [

{

"contenu": "<p>personnes</p>",

"langue": "fr"

},

{

"contenu": "<p>Persons</p>",

"langue": "en"

}

],

"titre": [

{

"contenu": "Unité de mesure",
